devices:
  - name: UDM-SE
    ip: 172.16.90.1
    type: ubiquiti
    services: [router, switch, firewall, cctv, wifi]

  - name: UAP-AC-1
    ip: 172.16.90.2
    type: ubiquiti
    services: [wifi]

  - name: UAP-AC-2
    ip: 172.16.90.3
    type: ubiquiti
    services: [wifi]

  - name: Proxmox
    ip: 172.16.90.50
    type: linux
    services: [hypervisor]

  - name: VM-Asterisk-Unai
    ip: 172.16.90.51
    type: linux
    services: [voip]

  - name: VM-Asterisk-Ariel
    ip: 172.16.90.52
    type: linux
    services: [voip]

  - name: VM-PiHole-Alex
    ip: 172.16.90.53
    type: linux
    services: [dns]

  - name: VM-NetAutoMon
    ip: 172.16.90.54
    type: linux
    services: [monitoring, automation]